### ISSUE TITLE
Can not run test command

### ISSUE THREAD

**Issue by dimamarksman** [SAP/fundamental-styles#1325]
**Describe the bug**
Running `npm test` command fails with `Error: Docker Chromium: Failed to build Docker image`.

> Is this issue related to a specific component?
No
> What version of the Fundamental Library Styles are you using?
0.11.3-rc.14

**To Reproduce**
1. Clone master
2. run `npm install`
3. run `npm test`

**Expected behavior**
Test command should run successfully (not `Exit status 1`)

**Screenshots**
![image](https://user-images.githubusercontent.com/3263744/89292591-44a61f00-d665-11ea-9ac8-591fd3614436.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Additional context**

**Comment by dimamarksman** [comment]
`debug.log` file looks like this:
```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'storybook:visual:setup'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [
4 verbose run-script   'prestorybook:visual:setup',
4 verbose run-script   'storybook:visual:setup',
4 verbose run-script   'poststorybook:visual:setup'
4 verbose run-script ]
5 info lifecycle fundamental-styles@0.11.3-rc.14~prestorybook:visual:setup: fundamental-styles@0.11.3-rc.14
6 info lifecycle fundamental-styles@0.11.3-rc.14~storybook:visual:setup: fundamental-styles@0.11.3-rc.14
7 verbose lifecycle fundamental-styles@0.11.3-rc.14~storybook:visual:setup: unsafe-perm in lifecycle true
8 verbose lifecycle fundamental-styles@0.11.3-rc.14~storybook:visual:setup: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\projects\fundamental-styles\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\1\bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\projects\fundamental-styles\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Users\1\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs;C:\Users\1\AppData\Local\Programs\Python\Python38-32\Scripts;C:\Users\1\AppData\Local\Programs\Python\Python38-32;C:\Users\1\AppData\Local\Microsoft\WindowsApps;C:\Users\1\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\1\AppData\Roaming\npm
9 verbose lifecycle fundamental-styles@0.11.3-rc.14~storybook:visual:setup: CWD: D:\projects\fundamental-styles
10 silly lifecycle fundamental-styles@0.11.3-rc.14~storybook:visual:setup: Args: [ '-c', 'jest --no-cache --config=./config/jest.config.js' ]
11 silly lifecycle fundamental-styles@0.11.3-rc.14~storybook:visual:setup: Returned: code: 1  signal: null
12 info lifecycle fundamental-styles@0.11.3-rc.14~storybook:visual:setup: Failed to exec storybook:visual:setup script
13 verbose stack Error: fundamental-styles@0.11.3-rc.14 storybook:visual:setup: `jest --no-cache --config=./config/jest.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid fundamental-styles@0.11.3-rc.14
15 verbose cwd D:\projects\fundamental-styles
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "storybook:visual:setup"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error fundamental-styles@0.11.3-rc.14 storybook:visual:setup: `jest --no-cache --config=./config/jest.config.js`
22 error Exit status 1
23 error Failed at the fundamental-styles@0.11.3-rc.14 storybook:visual:setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dimamarksman** [comment]
Turns out that `Docker` must be installed separately. 
Downloaded Docker [here](https://docs.docker.com/docker-for-windows/install/) and it started working.
